### PR TITLE
Updates architecture.md

### PR DESCRIPTION
**Pull request by chrisSCM**
Auto commit by GitBook Editor

### CODE REVIEW

**Comment by appinteractive** [comment]
This is not working as it uses assets that are behind a login

**Comment by chrisSCM** [comment]
It's only a comment for you - a note. Remember? Just delete it if you don't want to have it here...

**Comment by chrisSCM** [comment]
It's only text :-)  It works.

**Comment by appinteractive** [comment]
I remember 😁

**Comment by Lulalaby** [comment]
status?

**Comment by appinteractive** [comment]
We wanted to add a graph which illustrates the dependencies of all services. 
@Lulalaby could you add the last page or a screenshot of it to the docs?

[3.1.2.3 System Architecture-v6-20180919_0930.pdf](https://github.com/Human-Connection/Documentation/files/2395877/3.1.2.3.System.Architecture-v6-20180919_0930.pdf)

**Comment by Lulalaby** [comment]
okay 👍

**Pull request merged**
